import '../models/track.dart';
import '../models/recently_played_item.dart';
import '../models/playlist.dart';
import '../models/album.dart';

class MockTracks {
  static const List<Track> likedTracks = [
    Track(
      trackId: '1',
      title: 'God\'s Plan',
      streamUrl: 'https://example.com/audio1.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 5000000,
      likeCount: 142000,
      durationSeconds: 198,
      isLiked: true,
    ),
    Track(
      trackId: '2',
      title: 'HUMBLE.',
      streamUrl: 'https://example.com/audio2.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 4200000,
      likeCount: 98700,
      durationSeconds: 177,
      isLiked: true,
    ),
    Track(
      trackId: '3',
      title: 'Blinding Lights',
      streamUrl: 'https://example.com/audio3.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 8000000,
      likeCount: 210500,
      durationSeconds: 200,
      isLiked: true,
    ),
    Track(
      trackId: '4',
      title: 'SICKO MODE',
      streamUrl: 'https://example.com/audio4.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 6000000,
      likeCount: 187300,
      durationSeconds: 312,
      isLiked: true,
    ),
  ];

  static const Track hotTrack = Track(
    trackId: '5',
    title: 'luther',
    streamUrl: 'https://example.com/audio5.mp3',
    visibility: 'public',
    processingStatus: 'completed',
    playCount: 3000000,
    likeCount: 82000,
    durationSeconds: 228,
    isLiked: false,
  );

  static const List<Track> recommendedTracks = [
    Track(
      trackId: '6',
      title: 'fukumean',
      streamUrl: 'https://example.com/audio6.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 1200000,
      likeCount: 54000,
      durationSeconds: 149,
      isLiked: false,
    ),
    Track(
      trackId: '7',
      title: 'Rich Flex',
      streamUrl: 'https://example.com/audio7.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 2000000,
      likeCount: 76800,
      durationSeconds: 231,
      isLiked: false,
    ),
    Track(
      trackId: '8',
      title: 'Mask Off',
      streamUrl: 'https://example.com/audio8.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 1500000,
      likeCount: 43200,
      durationSeconds: 183,
      isLiked: false,
    ),
    Track(
      trackId: '9',
      title: 'ROCKSTAR',
      streamUrl: 'https://example.com/audio9.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 2500000,
      likeCount: 91500,
      durationSeconds: 178,
      isLiked: false,
    ),
  ];

  static const List<Track> historyTracks = [
    Track(
      trackId: '4',
      title: 'SICKO MODE',
      streamUrl: 'https://example.com/audio4.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 6000000,
      likeCount: 187300,
      durationSeconds: 312,
      isLiked: false,
    ),
    Track(
      trackId: '9',
      title: 'ROCKSTAR',
      streamUrl: 'https://example.com/audio9.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 2500000,
      likeCount: 91500,
      durationSeconds: 178,
      isLiked: false,
    ),
    Track(
      trackId: '2',
      title: 'HUMBLE.',
      streamUrl: 'https://example.com/audio2.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 4200000,
      likeCount: 98700,
      durationSeconds: 177,
      isLiked: false,
    ),
    Track(
      trackId: '1',
      title: 'God\'s Plan',
      streamUrl: 'https://example.com/audio1.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 5000000,
      likeCount: 142000,
      durationSeconds: 198,
      isLiked: false,
    ),
  ];

  static const List<Track> recentlyPlayedTracks = [
    Track(
      trackId: '8',
      title: 'Mask Off',
      streamUrl: 'https://example.com/audio8.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 1500000,
      likeCount: 43200,
      durationSeconds: 183,
      isLiked: false,
    ),
    Track(
      trackId: '3',
      title: 'Blinding Lights',
      streamUrl: 'https://example.com/audio3.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 8000000,
      likeCount: 210500,
      durationSeconds: 200,
      isLiked: false,
    ),
    Track(
      trackId: '9',
      title: 'ROCKSTAR',
      streamUrl: 'https://example.com/audio9.mp3',
      visibility: 'public',
      processingStatus: 'completed',
      playCount: 2500000,
      likeCount: 91500,
      durationSeconds: 178,
      isLiked: false,
    ),
  ];

  static List<RecentlyPlayedItem> get recentlyPlayedItems => [
    RecentlyPlayedPlaylist(
      Playlist(
        id: 'p1',
        userId: 'THRILLHO',
        name: 'Somatic  -  Deep Bass  -  Brain Massage',
        description: '',
        coverUrl: '',
        isPublic: true,
        trackCount: 23,
        tracks: [],
      ),
    ),
    RecentlyPlayedAlbum(
      Album(
        id: 'a1',
        title: 'Lana Del Rey - ULTRAVIOLENCE',
        artist: 'Interscope Records',
        releaseYear: 2014,
        artworkUrl: '',
        trackCount: 0,
        likeCount: 0,
      ),
    ),
    RecentlyPlayedPlaylist(
      Playlist(
        id: 'p2',
        userId: 'Hana_Ahmed',
        name: 'kennedy walsh jams',
        description: '',
        coverUrl: '',
        isPublic: true,
        trackCount: 112,
        tracks: [],
      ),
    ),
    RecentlyPlayedPlaylist(
      Playlist(
        id: 'p3',
        userId: 'New!',
        name: 'Buzzing Indie',
        description: '',
        coverUrl: '',
        isPublic: true,
        trackCount: 25,
        tracks: [],
      ),
    ),
    RecentlyPlayedPlaylist(
      Playlist(
        id: 'p4',
        userId: 'SoundCloud',
        name: 'Your Mix 1',
        description: '',
        coverUrl: '',
        isPublic: false,
        trackCount: 0,
        tracks: [],
      ),
    ),
  ];
}
