import '../models/track.dart';

class MockTracks {
  static const List<Track> likedTracks = [
    Track(
      id: '1',
      userId: 'user_1',
      userDisplayName: 'Drake',
      userProfilePicture: null,
      title: 'God\'s Plan',
      description: '',
      genre: 'Hip-Hop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track1/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 198,
      playCount: 0,
      likeCount: 142000,
      repostCount: 0,
      commentCount: 0,
      isLiked: true,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
    Track(
      id: '2',
      userId: 'user_2',
      userDisplayName: 'Kendrick Lamar',
      userProfilePicture: null,
      title: 'HUMBLE.',
      description: '',
      genre: 'Hip-Hop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track2/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 177,
      playCount: 0,
      likeCount: 98700,
      repostCount: 0,
      commentCount: 0,
      isLiked: true,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
    Track(
      id: '3',
      userId: 'user_3',
      userDisplayName: 'The Weeknd',
      userProfilePicture: null,
      title: 'Blinding Lights',
      description: '',
      genre: 'Pop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track3/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 200,
      playCount: 0,
      likeCount: 210500,
      repostCount: 0,
      commentCount: 0,
      isLiked: true,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
    Track(
      id: '4',
      userId: 'user_4',
      userDisplayName: 'Travis Scott',
      userProfilePicture: null,
      title: 'SICKO MODE',
      description: '',
      genre: 'Hip-Hop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track4/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 312,
      playCount: 0,
      likeCount: 187300,
      repostCount: 0,
      commentCount: 0,
      isLiked: true,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
  ];

  static const Track hotTrack = Track(
    id: '5',
    userId: 'user_2',
    userDisplayName: 'Kendrick Lamar ft. SZA',
    userProfilePicture: null,
    title: 'luther',
    description: '',
    genre: 'Hip-Hop',
    tags: [],
    artworkUrl: 'https://picsum.photos/seed/track5/150/150',
    fileUrl:
        'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
    visibility: 'public',
    duration: 228,
    playCount: 0,
    likeCount: 82000,
    repostCount: 0,
    commentCount: 0,
    isLiked: false,
    isReposted: false,
    releaseDate: null,
    createdAt: '2024-01-01T00:00:00Z',
  );

  static const List<Track> recommendedTracks = [
    Track(
      id: '6',
      userId: 'user_5',
      userDisplayName: 'Gunna',
      userProfilePicture: null,
      title: 'fukumean',
      description: '',
      genre: 'Hip-Hop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track6/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 149,
      playCount: 0,
      likeCount: 54000,
      repostCount: 0,
      commentCount: 0,
      isLiked: false,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
    Track(
      id: '7',
      userId: 'user_1',
      userDisplayName: 'Drake & 21 Savage',
      userProfilePicture: null,
      title: 'Rich Flex',
      description: '',
      genre: 'Hip-Hop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track7/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 231,
      playCount: 0,
      likeCount: 76800,
      repostCount: 0,
      commentCount: 0,
      isLiked: false,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
    Track(
      id: '8',
      userId: 'user_6',
      userDisplayName: 'Future',
      userProfilePicture: null,
      title: 'Mask Off',
      description: '',
      genre: 'Hip-Hop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track8/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 183,
      playCount: 0,
      likeCount: 43200,
      repostCount: 0,
      commentCount: 0,
      isLiked: false,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
    Track(
      id: '9',
      userId: 'user_7',
      userDisplayName: 'DaBaby ft. Roddy Ricch',
      userProfilePicture: null,
      title: 'ROCKSTAR',
      description: '',
      genre: 'Hip-Hop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track9/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 178,
      playCount: 0,
      likeCount: 91500,
      repostCount: 0,
      commentCount: 0,
      isLiked: false,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
  ];

  static const List<Track> historyTracks = [
    Track(
      id: '4',
      userId: 'user_4',
      userDisplayName: 'Travis Scott',
      userProfilePicture: null,
      title: 'SICKO MODE',
      description: '',
      genre: 'Hip-Hop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track4/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 312,
      playCount: 0,
      likeCount: 187300,
      repostCount: 0,
      commentCount: 0,
      isLiked: false,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
    Track(
      id: '9',
      userId: 'user_7',
      userDisplayName: 'DaBaby ft. Roddy Ricch',
      userProfilePicture: null,
      title: 'ROCKSTAR',
      description: '',
      genre: 'Hip-Hop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track9/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 178,
      playCount: 0,
      likeCount: 91500,
      repostCount: 0,
      commentCount: 0,
      isLiked: false,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
    Track(
      id: '2',
      userId: 'user_2',
      userDisplayName: 'Kendrick Lamar',
      userProfilePicture: null,
      title: 'HUMBLE.',
      description: '',
      genre: 'Hip-Hop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track2/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 177,
      playCount: 0,
      likeCount: 98700,
      repostCount: 0,
      commentCount: 0,
      isLiked: false,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
    Track(
      id: '1',
      userId: 'user_1',
      userDisplayName: 'Drake',
      userProfilePicture: null,
      title: 'God\'s Plan',
      description: '',
      genre: 'Hip-Hop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track1/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 198,
      playCount: 0,
      likeCount: 142000,
      repostCount: 0,
      commentCount: 0,
      isLiked: false,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
  ];

  static const List<Track> recentlyPlayedTracks = [
    Track(
      id: '8',
      userId: 'user_6',
      userDisplayName: 'Future',
      userProfilePicture: null,
      title: 'Mask Off',
      description: '',
      genre: 'Hip-Hop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track8/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 183,
      playCount: 0,
      likeCount: 43200,
      repostCount: 0,
      commentCount: 0,
      isLiked: false,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
    Track(
      id: '3',
      userId: 'user_3',
      userDisplayName: 'The Weeknd',
      userProfilePicture: null,
      title: 'Blinding Lights',
      description: '',
      genre: 'Pop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track3/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 200,
      playCount: 0,
      likeCount: 210500,
      repostCount: 0,
      commentCount: 0,
      isLiked: false,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
    Track(
      id: '9',
      userId: 'user_7',
      userDisplayName: 'DaBaby ft. Roddy Ricch',
      userProfilePicture: null,
      title: 'ROCKSTAR',
      description: '',
      genre: 'Hip-Hop',
      tags: [],
      artworkUrl: 'https://picsum.photos/seed/track9/150/150',
      fileUrl:
          'assets/audio/tadashikeiji-gods-got-my-love-life-handled-319926.mp3',
      visibility: 'public',
      duration: 178,
      playCount: 0,
      likeCount: 91500,
      repostCount: 0,
      commentCount: 0,
      isLiked: false,
      isReposted: false,
      releaseDate: null,
      createdAt: '2024-01-01T00:00:00Z',
    ),
  ];
}
